:- module(rules, [isDigit/2, isTeen/2, isTen/2, isHundred/2, isThousandOrHigherIdentifier/2, isOperator/2, isParenthesis/2]).

% All these rules are automatically generated by the python script
% `build_predicates.py` from the `databases` directory.
% It is based on the data stored in the *.txt files in the `databases` directory.

% source file: digits.txt
isDigit(["nula"], 0) :- !.
isDigit(["nulou"], 0) :- !.
isDigit(["jedna"], 1) :- !.
isDigit(["jednou"], 1) :- !.
isDigit(["jedno"], 1) :- !.
isDigit(["jedním"], 1) :- !.
isDigit(["jednim"], 1) :- !.
isDigit(["jeden"], 1) :- !.
isDigit(["dva"], 2) :- !.
isDigit(["dvě"], 2) :- !.
isDigit(["dve"], 2) :- !.
isDigit(["dvěma"], 2) :- !.
isDigit(["dvema"], 2) :- !.
isDigit(["tři"], 3) :- !.
isDigit(["tri"], 3) :- !.
isDigit(["třemi"], 3) :- !.
isDigit(["tremi"], 3) :- !.
isDigit(["čtyři"], 4) :- !.
isDigit(["ctyri"], 4) :- !.
isDigit(["čtyřmi"], 4) :- !.
isDigit(["ctyrmi"], 4) :- !.
isDigit(["pět"], 5) :- !.
isDigit(["pet"], 5) :- !.
isDigit(["pěti"], 5) :- !.
isDigit(["peti"], 5) :- !.
isDigit(["šest"], 6) :- !.
isDigit(["sest"], 6) :- !.
isDigit(["šesti"], 6) :- !.
isDigit(["sesti"], 6) :- !.
isDigit(["sedm"], 7) :- !.
isDigit(["sedmi"], 7) :- !.
isDigit(["osm"], 8) :- !.
isDigit(["osmi"], 8) :- !.
isDigit(["devět"], 9) :- !.
isDigit(["devet"], 9) :- !.
isDigit(["devíti"], 9) :- !.
isDigit(["deviti"], 9) :- !.


% source file: teens.txt
isTeen(["deset"], 10) :- !.
isTeen(["jedenáct"], 11) :- !.
isTeen(["jedenact"], 11) :- !.
isTeen(["dvanáct"], 12) :- !.
isTeen(["dvanact"], 12) :- !.
isTeen(["třináct"], 13) :- !.
isTeen(["trinact"], 13) :- !.
isTeen(["čtrnáct"], 14) :- !.
isTeen(["ctrnact"], 14) :- !.
isTeen(["patnáct"], 15) :- !.
isTeen(["patnact"], 15) :- !.
isTeen(["šestnáct"], 16) :- !.
isTeen(["sestnact"], 16) :- !.
isTeen(["sedmnáct"], 17) :- !.
isTeen(["sedmnact"], 17) :- !.
isTeen(["osmnáct"], 18) :- !.
isTeen(["osmnact"], 18) :- !.
isTeen(["devatenáct"], 19) :- !.
isTeen(["devatenact"], 19) :- !.
isTeen(["deseti"], 10) :- !.
isTeen(["jedenácti"], 11) :- !.
isTeen(["jedenacti"], 11) :- !.
isTeen(["dvanácti"], 12) :- !.
isTeen(["dvanacti"], 12) :- !.
isTeen(["třinácti"], 13) :- !.
isTeen(["trinacti"], 13) :- !.
isTeen(["čtrnácti"], 14) :- !.
isTeen(["ctrnacti"], 14) :- !.
isTeen(["patnácti"], 15) :- !.
isTeen(["patnacti"], 15) :- !.
isTeen(["šestnácti"], 16) :- !.
isTeen(["sestnacti"], 16) :- !.
isTeen(["sedmnácti"], 17) :- !.
isTeen(["sedmnacti"], 17) :- !.
isTeen(["osmnácti"], 18) :- !.
isTeen(["osmnacti"], 18) :- !.
isTeen(["devatenácti"], 19) :- !.
isTeen(["devatenacti"], 19) :- !.


% source file: tens.txt
isTen(["dvacet"], 20) :- !.
isTen(["třicet"], 30) :- !.
isTen(["tricet"], 30) :- !.
isTen(["čtyřicet"], 40) :- !.
isTen(["ctyricet"], 40) :- !.
isTen(["padesát"], 50) :- !.
isTen(["padesat"], 50) :- !.
isTen(["šedesát"], 60) :- !.
isTen(["sedesat"], 60) :- !.
isTen(["sedmdesát"], 70) :- !.
isTen(["sedmdesat"], 70) :- !.
isTen(["osmdesát"], 80) :- !.
isTen(["osmdesat"], 80) :- !.
isTen(["devadesát"], 90) :- !.
isTen(["devadesat"], 90) :- !.
isTen(["dvaceti"], 20) :- !.
isTen(["třiceti"], 30) :- !.
isTen(["triceti"], 30) :- !.
isTen(["čtyřiceti"], 40) :- !.
isTen(["ctyriceti"], 40) :- !.
isTen(["padesáti"], 50) :- !.
isTen(["padesati"], 50) :- !.
isTen(["šedesáti"], 60) :- !.
isTen(["sedesati"], 60) :- !.
isTen(["sedmdesáti"], 70) :- !.
isTen(["sedmdesati"], 70) :- !.
isTen(["osmdesáti"], 80) :- !.
isTen(["osmdesati"], 80) :- !.
isTen(["devadesáti"], 90) :- !.
isTen(["devadesati"], 90) :- !.


% source file: hundreds.txt
isHundred(["sto"], 100) :- !.
isHundred(["stem"], 100) :- !.
isHundred(["jedno", "sto"], 100) :- !.
isHundred(["jedním", "stem"], 100) :- !.
isHundred(["jednim", "stem"], 100) :- !.
isHundred(["dvě", "sta"], 200) :- !.
isHundred(["dve", "sta"], 200) :- !.
isHundred(["dvěma", "sty"], 200) :- !.
isHundred(["dvema", "sty"], 200) :- !.
isHundred(["dvě", "stě"], 200) :- !.
isHundred(["dve", "ste"], 200) :- !.
isHundred(["tři", "sta"], 300) :- !.
isHundred(["tri", "sta"], 300) :- !.
isHundred(["třemi", "sty"], 300) :- !.
isHundred(["tremi", "sty"], 300) :- !.
isHundred(["čtyři", "sta"], 400) :- !.
isHundred(["ctyri", "sta"], 400) :- !.
isHundred(["čtyřmi", "sty"], 400) :- !.
isHundred(["ctyrmi", "sty"], 400) :- !.
isHundred(["pět", "set"], 500) :- !.
isHundred(["pet", "set"], 500) :- !.
isHundred(["pěti", "sty"], 500) :- !.
isHundred(["peti", "sty"], 500) :- !.
isHundred(["šest", "set"], 600) :- !.
isHundred(["sest", "set"], 600) :- !.
isHundred(["šesti", "sty"], 600) :- !.
isHundred(["sesti", "sty"], 600) :- !.
isHundred(["sedm", "set"], 700) :- !.
isHundred(["sedmi", "sty"], 700) :- !.
isHundred(["osm", "set"], 800) :- !.
isHundred(["osmi", "sty"], 800) :- !.
isHundred(["devět", "set"], 900) :- !.
isHundred(["devet", "set"], 900) :- !.
isHundred(["devíti", "sty"], 900) :- !.
isHundred(["deviti", "sty"], 900) :- !.


% source file: identifiers.txt
isThousandOrHigherIdentifier(["tisíc"], 1000) :- !.
isThousandOrHigherIdentifier(["tisic"], 1000) :- !.
isThousandOrHigherIdentifier(["tisíce"], 1000) :- !.
isThousandOrHigherIdentifier(["tisice"], 1000) :- !.
isThousandOrHigherIdentifier(["tisícem"], 1000) :- !.
isThousandOrHigherIdentifier(["tisicem"], 1000) :- !.
isThousandOrHigherIdentifier(["tisíci"], 1000) :- !.
isThousandOrHigherIdentifier(["tisici"], 1000) :- !.
isThousandOrHigherIdentifier(["milion"], 1000000) :- !.
isThousandOrHigherIdentifier(["milionem"], 1000000) :- !.
isThousandOrHigherIdentifier(["milionů"], 1000000) :- !.
isThousandOrHigherIdentifier(["milionu"], 1000000) :- !.
isThousandOrHigherIdentifier(["miliony"], 1000000) :- !.
isThousandOrHigherIdentifier(["miliarda"], 1000000000) :- !.
isThousandOrHigherIdentifier(["miliardou"], 1000000000) :- !.
isThousandOrHigherIdentifier(["miliardy"], 1000000000) :- !.
isThousandOrHigherIdentifier(["miliard"], 1000000000) :- !.
isThousandOrHigherIdentifier(["miliardami"], 1000000000) :- !.
isThousandOrHigherIdentifier(["bilion"], 1000000000000) :- !.
isThousandOrHigherIdentifier(["bilionem"], 1000000000000) :- !.
isThousandOrHigherIdentifier(["bilionů"], 1000000000000) :- !.
isThousandOrHigherIdentifier(["bilionu"], 1000000000000) :- !.
isThousandOrHigherIdentifier(["biliony"], 1000000000000) :- !.
isThousandOrHigherIdentifier(["biliarda"], 1000000000000000) :- !.
isThousandOrHigherIdentifier(["biliardou"], 1000000000000000) :- !.
isThousandOrHigherIdentifier(["biliardy"], 1000000000000000) :- !.
isThousandOrHigherIdentifier(["biliard"], 1000000000000000) :- !.
isThousandOrHigherIdentifier(["biliardami"], 1000000000000000) :- !.
isThousandOrHigherIdentifier(["trilion"], 1000000000000000000) :- !.
isThousandOrHigherIdentifier(["trilionem"], 1000000000000000000) :- !.
isThousandOrHigherIdentifier(["trilionů"], 1000000000000000000) :- !.
isThousandOrHigherIdentifier(["trilionu"], 1000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliony"], 1000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliarda"], 1000000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliardou"], 1000000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliardy"], 1000000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliard"], 1000000000000000000000) :- !.
isThousandOrHigherIdentifier(["triliardami"], 1000000000000000000000) :- !.


% source file: operators.txt
isOperator(["plus"], +) :- !.
isOperator(["mínus"], -) :- !.
isOperator(["minus"], -) :- !.
isOperator(["krát"], *) :- !.
isOperator(["krat"], *) :- !.
isOperator(["děleno"], /) :- !.
isOperator(["deleno"], /) :- !.


% source file: parentheses.txt
isParenthesis(["závorka"], '(') :- !.
isParenthesis(["zavorka"], '(') :- !.
isParenthesis(["konec", "závorky"], ')') :- !.
isParenthesis(["konec", "zavorky"], ')') :- !.


